<!doctype html>

          
<div id="content">
<div class="outer">
<div class="inner bg-light lter">
<div class="col-lg-12">
<h1>bootstrap-admin-template</h1>


<ul>
<li><a href="welcome/login">Login</a></li>

<li><a href="https://travis-ci.org/Osman%20Nuri%20Okumus/bootstrap-admin-template"><img src="https://img.shields.io/travis/Osman%20Nuri%20Okumus/bootstrap-admin-template.svg?style=flat" alt="Build Status"></a></li>
<li><a href="https://david-dm.org/puikinsh/Bootstrap-Admin-Template"><img src="https://david-dm.org/puikinsh/Bootstrap-Admin-Template.svg?theme=shields.io" alt="Dependency Status"></a></li>
<li><a href="https://david-dm.org/puikinsh/Bootstrap-Admin-Template#info=devDependencies"><img src="https://david-dm.org/puikinsh/Bootstrap-Admin-Template/dev-status.svg?theme=shields.io" alt="devDependency Status"></a></li>
</ul>
<h2>TOC</h2>
<ul>
<li><a href="#download">Download</a>
<ul>
<li><a href="#building">Building</a></li>
<li><a href="#demo">Demo</a></li>
<li><a href="#release-history">Release History</a></li>
<li><a href="#credits">Credits</a></li>
<li><a href="#author">Author</a></li>
<li><a href="#license">License</a></li>
</ul></li>
</ul>
<h2>Download</h2>

<h2>About Authors</h2>
<ul>
<li><a href="https://colorlib.com/">Colorlib</a> - Colorlib is the most popular source for free WordPress themes and HTML templates.</li>
<li><a href="https://twitter.com/AigarsSilkalns">Aigars Silkalns</a> - Aigars maintains this project and is also the idea author behind Colorlib and everythiwn you will find on that website.</li>
</ul>
<h2>License</h2>
<p>Copyright (c) 2016 Aigars Silkalns & Colorlib</p>
<p>Released under the MIT license. This free Bootstrap admin template is distributed as as it with no support. You can feeel free to use it, share it, tweakit it, workin it, sell it or do whatver you want as long as you keep the original license in plce.</p>
<hr>
<p><em>This file was generated by <a href="https://github.com/verbose/verb">verb</a>, v0.9.0, on July 31, 2016.</em></p>

</div>

                        </div>
                        <!-- /.inner -->
                    </div>
                    <!-- /.outer -->
                </div>
                <!-- /#content -->

           
           